### ISSUE TITLE
status-json.xsl not working

### ISSUE THREAD

**Issue by klauskobald** [xiph/Icecast-Server#55]
icecast2 -v
Icecast 2.4.4

http://****:8000/status-json.xsl

404 - Could not parse XSLT file

I cannot find a solution anywhere. I stumbled across a site where status-json is mentioned as deprecated.
So how do I get stats?

thanks

stats-json does indeed not exist
<img width="168" alt="image" src="https://user-images.githubusercontent.com/278428/189486321-59ecfccc-8856-4251-85bd-9d5fbc99075f.png">

**Comment by phschafft** [comment]
Good morning,

`status-json.xsl` is deprecated. What is not deprecated is all below `/admin/` (the actual API). Plus for 2.5.x there is a new `/admin/publicstats` endpoint that is kind-of the successor of `status-json.xsl`.

`status-json.xsl` is an optional part (meaning it is installed by default but operators sometimes choose to remove it). While being deprecated it is still provided at this point. If your installation lacks it it's most likely because someone removed it (which might or might not have a reason). You can however you reinstall it by copying the latest versions of `status-json.xsl`, and `xml2json.xslt` (both located in `/web/`).

Side note A: `status2.xsl` has been removed from the official distribution before version 2.4.0. Maybe the inconstant state of your `/web/` could be due to an upgrade that gone wrong?
Side note B: This is not the official ticket system. Hence it takes a lot longer to get any answer here. You can find the official one here: https://gitlab.xiph.org/xiph/icecast-server/-/issues
